# 数据源
spring:
  datasource:
    ### 在同一个网络中，bridge  pro-net   容器之间不仅可以通过ip访问，而且可以通过名称
    #url: jdbc:mysql://my-mysql:3306/springboot_mybatis_demo_DB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://172.16.107.140:3304/springboot_mybatis_demo_DB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wtf15
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis托管mapper文件
mybatis:
  mapper-locations: classpath:mapper/*.xml



